#!/bin/csh

#  ejw, 28-sep-01

set num = `echo $CLON_DAQ | sed "s/^....//"`


if ($1 == start) then

  ssh -n $CLON_DAQ "ipcbank2et -a $2 -s $3 >>& $CLON_LOG/run_log/ipcbank2et.log &" &

else if ($1 == stop) then

  echo "Terminating ipcbank2et for exp=$2 on $CLON_DAQ .."
  stop_ipc_proc -a $2 -i ipcbank2et -n $CLON_DAQ -p ipcbank2et >& /dev/null

else 
    echo ""
    echo "   ?illegal arg: $1"
    echo ""
endif
