#!/bin/csh

#

if ($1 == start) then

  ssh -n $CLON_DAQ "(run_log_update -a $2 -s $3) >>& $CLON_LOG/run_log/run_log_update.log &" &

else if ($1 == stop) then

  echo "Terminating run_log_update for exp=$2 on $CLON_DAQ .."
  stop_ipc_proc -a $2 -i run_log_update -n $CLON_DAQ -p run_log_update >& /dev/null

else 
    echo ""
    echo "   ?illegal arg: $1"
    echo ""
endif
