#!/bin/csh -f


#
#                taggermac  svt333                      
#                adcpcal1
#                pgem       prad1      prad2    prad3
#                mvt2
#                svt3
#                test6      test5  test7
#
#                129.57.160.138  129.57.86.47
#                129.57.167.81
#                129.57.160.146  129.57.160.147  129.57.160.148  129.57.160.149
#                129.57.160.216
#                129.57.86.79
#                129.57.86.79    129.57.86.144    129.57.86.122
#


set ch       = " "
set rocs     = ""
set crates   = ""
set vme      = "-crate"
##set hostname = `hostname -s`
set NN=0
set flag = 0

# WIENER VME/VME64/VXS crates
set wiener_snmp =   ( dc11       dc12       dc13       dc21       dc22       dc23       dc31       dc32       \
                      dc33       dc41       dc42       dc43       dc51       dc52       dc53       dc61       \
                      dc62       dc63       tage1      taggermac  adccnd1    ioctest0   scaler1    pcal0      \
                      test1      tdcctof1   adcecal1   svt1       adcband1   hps1       hps2       tdcecal1   \
                      tdcpcal1   tdcftof1   adcpcal1   adcftof1   adcecal1   adcftof6   tdcftof6   adcpcal6   \
                      tdcpcal6   adcecal6   tdcecal6   adcecal5   tdcecal5   adcpcal5   tdcpcal5   adcftof5   \
                      tdcftof5   adcecal4   tdcecal4   adcpcal4   tdcpcal4   adcftof4   tdcftof4   adcecal2   \
                      tdcecal2   adcpcal2   tdcpcal2   adcftof2   tdcftof2   adcecal3   tdcecal3   adcpcal3   \
                      tdcpcal3   adcftof3   tdcftof3   hps11      highbtest3 dcrb2      trig1      trig2      \
                      svt2       adcctof1   mvt1       mmft1      adcft1     adcft2     adcft3     pgem       \
                      prad1      prad2      prad3      rich4      mvt2       tdcband1   test0      test2      \
                      classc10   mvt3       svt3       test3      bdx0       test4      prad0      test6      \
                      test5      test7      adchycal1  adchycal2  adchycal3  adchycal4  adchycal5  adchycal6  \
                      adchycal7  gem0       gem1       gem2       mpd1       trig0      mpd2       mpd3 )

# TRIPPLITE-powered devices
set tripplite_snmp = ( clondaq11 clondaq12 clondaq14 srs1 classchv atca1 clondaq10 clondaq9)




#*** print help message if -h or -help specified ***
if ($#argv == 0 ) then
  set flag = 1
endif
if ($flag == 0 ) then
  if (($argv[1] == "h") || ($argv[1] == "-h") || ($argv[1] == "--h") || \
      ($argv[1] == "help") || ($argv[1] == "-help") || ($argv[1] == "--help")) then
    set flag = 2
  endif
endif
if ($flag != 0 ) then
  set elements_per_line = 8
  echo ""
  echo "  Usage: roc_reboot ROC_name [or ROCs_list]"
  echo "  -----------------------------------------"
  echo "  Example: list of possible ROC names:"
  echo "    tdctof1 - tdctof6  tdcecal1 - tdcecal6  tdcpcal1 - tdcpcal6"
  echo "    adctof1 - adctof6  adcecal1 - adcecal6  adcpcal1 - adcpcal6"
  echo "  --------------------------------------------"
  echo "  Example: ROCs_list could be any string with ROC names"
  echo "    with commas: tdctof1, adcecal1, .. , tdcpcal6"
  echo "    with dashes: adctof1 - adctof6, tdcpcal1 - tdcpcal6"
  echo "    and mixture: adctof1 - adctof6  tdctof6, , adcecal6, tdcpcal1 - tdcpcal6"
  echo ""
  echo "=== List of currently registered WIENER VME/VME64/VXS crates:"
  set count = 0
  foreach name ($wiener_snmp)
    echo -n "$name   "
    @ count++
    if ($count % $elements_per_line == 0) then
        echo "" # Print a newline
    endif
  end
  echo ""
  echo ""
  echo "=== List of currently registered TRIPPLITE-powered devices:"
  set count = 0
  foreach name ($tripplite_snmp)
    echo -n "$name   "
    @ count++
    if ($count % $elements_per_line == 0) then
        echo "" # Print a newline
    endif
  end
  echo ""
  echo ""

  exit(0)
endif



#*** remove extra spaces and commas from input string ***
set spstr = `echo $argv  | perl -ple 's/\s+-\s+/-/g' | perl -ple 's/-\s+/-/g' | perl -ple 's/\s+-/-/g' | perl -ple 's/,/ /g' | perl -ple 's/\s+/ /g' `
#echo "spstr >$spstr<"; echo "N_spstr = $#spstr   spstr[1]=$spstr[1]"


foreach pre_roc ($spstr)
#echo ".... top_of_foreach:  pre_roc  >$pre_roc<"


#*** check if dash exist, and get number of words separated by dash ***
  set rr = `echo $pre_roc | grep -- '-' | awk -F- '{print $1" "$2" "$3" "$4 }' | wc | awk '{print $2}'`
#echo "rr = $rr"


# if no dash, then check existance of roc name $pre_roc
  if ( $rr == 0 ) then

    set ns_rr = `nslookup $pre_roc | grep -i "can't"`
    if ( $#ns_rr > 0 ) then
      echo ""
      echo " ERROR1: nslookup did not find IP name '$pre_roc'"
      echo ""
      exit(1)
    endif
    @ NN++
    set rocs = `echo "$rocs$ch$pre_roc" `
    set crates = `echo "$crates$ch$pre_roc$vme" `
    #echo "rocs    >$rocs<";   echo "rocs[$NN]  >$rocs[$NN]<"
    #echo "crates  >$crates<"; echo "crates[$NN]  >$crates[$NN]<"

#*** if dash found, then check existance of roc list in $pre_roc ***
  else if ( $rr == 2 ) then

    set roc_n = `echo $pre_roc | perl -ple 's/[^\d.]+/ /g'`
    #echo "roc_n  >$roc_n<"; echo "numb.roc_n = $#roc_n"
    if ( $#roc_n != 2 ) then
      echo ""
      echo " Wrong decimals in roc names : $pre_roc"
      echo ""
      exit(2)
    endif

    set ro = `echo $pre_roc | perl -ple 's/\d+-\S+/ /g'`
    set jj = $roc_n[1]

    while ( $jj <= $roc_n[2] )
      set roc =  `echo "$ro$jj" `
      set ns_rr = `nslookup $roc | grep -i "can't"`
      if ( $#ns_rr > 0 ) then
        echo ""
        echo " ERROR2: nslookup did not find IP name '$roc'"
        echo ""
        exit(3)
      endif
      @ NN++
      set rocs = `echo "$rocs$ch$roc" `
      set crates = `echo "$crates$ch$roc$vme" `
      #echo "rocs    >$rocs<";   echo "rocs[$NN]  >$rocs[$NN]<"
      #echo "crates  >$crates<"; echo "crates[$NN]  >$crates[$NN]<"

      @ jj++
    end

#*** dash found, but single or in wrong place ***
  else
    echo ""
    echo " Wrong input string : $pre_roc"
    echo ""
    exit(4)
  endif

end   # of foreach pre_roc ($spstr)






# check if name is listed in any of the lists above
foreach roc ($rocs)
  set ii = 0
  foreach wiener ($wiener_snmp)
    if ($roc == $wiener ) set ii = 1
  end
  foreach tripplite ($tripplite_snmp)
    if ($roc == $tripplite ) set ii = 2
  end
  ##echo "ii=$ii"

  if ( $ii == 0 ) then
    echo ""
    echo " Unknown name. Please check the name, use -h for help."
    echo ""
    exit (-1)
  endif
end




# reboot for wiener

if ( $ii == 1 ) then

  set jj = 1
  foreach roc ($rocs)

    set cmd   = `echo "snmpset -v 1 -c private $crates[$jj] enterprises.19947.1.1.1.0 i 0" `
    #echo $cmd
    echo "... $roc power turned OFF"
##    set stat = `ssh $hostname $cmd >& /dev/null & `
    snmpset -v 1 -c private $crates[$jj] enterprises.19947.1.1.1.0 i 0
    @ jj++
  end

  echo "... wait 5 seconds for power to be turned ON"
  sleep 5

  #*** finish reboot processes ***
  set jj = 1
  foreach roc ($rocs)
    set cmd   = `echo "snmpset -v 1 -c private $crates[$jj] enterprises.19947.1.1.1.0 i 1" `
    #echo $cmd
##    set stat = `ssh $hostname $cmd >& /dev/null & `
    snmpset -v 1 -c private $crates[$jj] enterprises.19947.1.1.1.0 i 1
    @ jj++
  end

endif



# reboot for tripplite

if ( $ii == 2 ) then

  foreach device ($rocs)
    echo "rebooting $device"

    if ( $roc == "clondaq11" ) then  #special case
      ## This part turns off the external clock for the FEUs before rebooting
      ## if coda in prestart/go state
      ##foreach mod ($atof_modules)
      ##  tcpClient clondaq11 petiroc_set_clk($mod,0)
      ##endif
      ## if coda is off or in configure/download
      #ssh clondaq11 '/usr/clas12/release/1.4.0/coda/src/rol/Linux_x86_64/bin/petiroc_setclk     0'
      #sleep 3
      snmpset -v 2c -c tripplite hallb-pdu-2 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.2 i 1
      sleep 5
      snmpset -v 2c -c tripplite hallb-pdu-2 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.2 i 2
    else if ( $roc == "clondaq12" ) then  #special case
      snmpset -v 2c -c tripplite hallb-pdu-2 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.4 i 1
      sleep 5
      snmpset -v 2c -c tripplite hallb-pdu-2 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.4 i 2
    else if ( $roc == "clondaq14" ) then  #special case
      snmpset -v 2c -c tripplite hallb-pdu-3 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.2 i 1
      sleep 10
      snmpset -v 2c -c tripplite hallb-pdu-3 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.2 i 2
    else if ( $roc == "srs1" ) then  #special case
      snmpset -v 2c -c tripplite hallb-pdu-3 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.3 i 1
      sleep 5
      snmpset -v 2c -c tripplite hallb-pdu-3 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.3 i 2
    else if ( $roc == "classchv" ) then  #special case
      snmpset -v 2c -c tripplite hallb-pdu-4 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.7 i 1
      sleep 5
      snmpset -v 2c -c tripplite hallb-pdu-4 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.7 i 2
    else if ( $roc == "atca1" ) then  #special case
      snmpset -v 2c -c tripplite hallb-pdu-6 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.1 i 1
      sleep 5
      snmpset -v 2c -c tripplite hallb-pdu-6 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.1 i 2
    else if ( $roc == "clondaq10" ) then  #special case
      snmpset -v 2c -c tripplite hallb-pdu-6 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.2 i 1
      sleep 5
      snmpset -v 2c -c tripplite hallb-pdu-6 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.2 i 2
    else if ( $roc == "clondaq9" ) then  #special case
      snmpset -v 2c -c tripplite hallb-pdu-6 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.3 i 1
      sleep 5
      snmpset -v 2c -c tripplite hallb-pdu-6 TRIPPLITE-PRODUCTS::tlpPduOutletCommand.1.3 i 2
    endif

  end

endif



exit(0)
