# SAMPA Global Control/Clk

set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVDS_25} [get_ports sampa_bx_sync_trig_n]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVDS_25} [get_ports sampa_bx_sync_trig_p]
set_property -dict {PACKAGE_PIN AA21 IOSTANDARD LVDS_25} [get_ports sampa_adc_clk_n]
set_property -dict {PACKAGE_PIN AA20 IOSTANDARD LVDS_25} [get_ports sampa_adc_clk_p]
set_property -dict {PACKAGE_PIN Y22 IOSTANDARD LVDS_25} [get_ports sampa_bx_clk_n]
set_property -dict {PACKAGE_PIN Y21 IOSTANDARD LVDS_25} [get_ports sampa_bx_clk_p]
set_property -dict {PACKAGE_PIN AB22 IOSTANDARD LVDS_25} [get_ports sampa_hbeat_trig_n]
set_property -dict {PACKAGE_PIN AB21 IOSTANDARD LVDS_25} [get_ports sampa_hbeat_trig_p]
set_property -dict {PACKAGE_PIN R14 IOSTANDARD LVDS_25} [get_ports sampa_hard_rst_n]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVDS_25} [get_ports sampa_hard_rst_p]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVDS_25} [get_ports sampa_trig_n]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVDS_25} [get_ports sampa_trig_p]

# SAMPA Global Config Pins

set_property -dict {PACKAGE_PIN T21 IOSTANDARD LVCMOS25} [get_ports {sampa_cg[0]}]
set_property -dict {PACKAGE_PIN U21 IOSTANDARD LVCMOS25} [get_ports {sampa_cg[1]}]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS25} [get_ports sampa_cts]
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS25} [get_ports sampa_pol]
set_property -dict {PACKAGE_PIN AB20 IOSTANDARD LVCMOS25} [get_ports {sampa_clk_config[0]}]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS25} [get_ports {sampa_clk_config[1]}]
set_property -dict {PACKAGE_PIN W17 IOSTANDARD LVCMOS25} [get_ports {sampa_clk_config[2]}]
set_property -dict {PACKAGE_PIN AA18 IOSTANDARD LVCMOS25} [get_ports {sampa_clk_config[3]}]
set_property -dict {PACKAGE_PIN AB18 IOSTANDARD LVCMOS25} [get_ports {sampa_clk_config[4]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS25} [get_ports {sampa_clk_config[5]}]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS25} [get_ports {sampa_clk_config[6]}]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS25} [get_ports sampa_pwr_enable_ana]
set_property -dict {PACKAGE_PIN W21 IOSTANDARD LVCMOS25} [get_ports sampa_pwr_enable_dig]
set_property -dict {PACKAGE_PIN T3 IOSTANDARD LVCMOS25} [get_ports sampa_por]
set_property -dict {PACKAGE_PIN F15 IOSTANDARD LVCMOS25} [get_ports sampa_por_valid]

# GPIO

set_property -dict {PACKAGE_PIN W22 IOSTANDARD LVCMOS25} [get_ports {tlk_tx[0]}]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS25} [get_ports {tlk_tx[1]}]
set_property -dict {PACKAGE_PIN AA19 IOSTANDARD LVCMOS25} [get_ports tlk_rx]
set_property -dict {PACKAGE_PIN P20 IOSTANDARD LVCMOS25} [get_ports padboard_id]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS25} [get_ports {led[0]}]
set_property -dict {PACKAGE_PIN L6 IOSTANDARD LVCMOS25} [get_ports {led[1]}]
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS25} [get_ports {led[2]}]
set_property -dict {PACKAGE_PIN M17 IOSTANDARD LVCMOS25} [get_ports {led[3]}]
set_property -dict {PACKAGE_PIN V22 IOSTANDARD LVCMOS25} [get_ports {lemo_out[0]}]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS25} [get_ports {lemo_out[1]}]

# SFP, MGT, Clks

set_property -dict {PACKAGE_PIN E6} [get_ports mgt0_ref_clk_n]
set_property -dict {PACKAGE_PIN F6} [get_ports mgt0_ref_clk_p]
set_property -dict {PACKAGE_PIN A8} [get_ports gth_rx_n]
set_property -dict {PACKAGE_PIN B8} [get_ports gth_rx_p]
set_property -dict {PACKAGE_PIN A4} [get_ports gth_tx_n]
set_property LOC GTPE2_CHANNEL_X0Y4 [get_cells phy_io_0/phy_driver_i/phy_wrapper_0/gtwizard_i/U0/gtwizard_0_init_i/gtwizard_0_i/gt0_gtwizard_0_i/gtpe2_i]
set_property -dict {PACKAGE_PIN B4} [get_ports gth_tx_p]
set_property -dict {PACKAGE_PIN E10} [get_ports mgt1_ref_clk_n]
set_property -dict {PACKAGE_PIN F10} [get_ports mgt1_ref_clk_p]
set_property -dict {PACKAGE_PIN V19 IOSTANDARD LVCMOS25} [get_ports mgt_recovered_clk_n]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS25} [get_ports mgt_recovered_clk_p]

# System Clock

set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVDS_25} [get_ports sys_clk_n]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVDS_25} [get_ports sys_clk_p]

# SAMPA 0

set_property -dict {PACKAGE_PIN F14 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_n[0]}]
set_property -dict {PACKAGE_PIN F13 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_p[0]}]
set_property -dict {PACKAGE_PIN C15 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_n[0]}]
set_property -dict {PACKAGE_PIN C14 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_p[0]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_n[10]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_p[10]}]
set_property -dict {PACKAGE_PIN A14 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_n[1]}]
set_property -dict {PACKAGE_PIN A13 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_p[1]}]
set_property -dict {PACKAGE_PIN A16 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_n[2]}]
set_property -dict {PACKAGE_PIN A15 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_p[2]}]
set_property -dict {PACKAGE_PIN A19 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_n[3]}]
set_property -dict {PACKAGE_PIN A18 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_p[3]}]
set_property -dict {PACKAGE_PIN B16 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_n[4]}]
set_property -dict {PACKAGE_PIN B15 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_p[4]}]
set_property -dict {PACKAGE_PIN D22 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_n[5]}]
set_property -dict {PACKAGE_PIN E22 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_p[5]}]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_n[6]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_p[6]}]
set_property -dict {PACKAGE_PIN B13 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_n[7]}]
set_property -dict {PACKAGE_PIN C13 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_p[7]}]
set_property -dict {PACKAGE_PIN B22 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_n[8]}]
set_property -dict {PACKAGE_PIN C22 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_p[8]}]
set_property -dict {PACKAGE_PIN E14 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_n[9]}]
set_property -dict {PACKAGE_PIN E13 IOSTANDARD PPDS_25} [get_ports {sampa0_sdo_p[9]}]

# SAMPA 1

set_property -dict {PACKAGE_PIN D15 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_n[1]}]
set_property -dict {PACKAGE_PIN D14 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_p[1]}]
set_property -dict {PACKAGE_PIN B18 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_n[0]}]
set_property -dict {PACKAGE_PIN B17 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_p[0]}]
set_property -dict {PACKAGE_PIN G22 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_n[10]}]
set_property -dict {PACKAGE_PIN G21 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_p[10]}]
set_property -dict {PACKAGE_PIN E17 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_n[1]}]
set_property -dict {PACKAGE_PIN F16 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_p[1]}]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_n[2]}]
set_property -dict {PACKAGE_PIN B21 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_p[2]}]
set_property -dict {PACKAGE_PIN C17 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_n[3]}]
set_property -dict {PACKAGE_PIN D17 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_p[3]}]
set_property -dict {PACKAGE_PIN C19 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_n[4]}]
set_property -dict {PACKAGE_PIN C18 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_p[4]}]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_n[5]}]
set_property -dict {PACKAGE_PIN E19 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_p[5]}]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_n[6]}]
set_property -dict {PACKAGE_PIN F18 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_p[6]}]
set_property -dict {PACKAGE_PIN D21 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_n[7]}]
set_property -dict {PACKAGE_PIN E21 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_p[7]}]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_n[8]}]
set_property -dict {PACKAGE_PIN F19 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_p[8]}]
set_property -dict {PACKAGE_PIN D16 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_n[9]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD PPDS_25} [get_ports {sampa1_sdo_p[9]}]

# SAMPA 2

set_property -dict {PACKAGE_PIN H22 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_n[2]}]
set_property -dict {PACKAGE_PIN J22 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_p[2]}]
set_property -dict {PACKAGE_PIN G20 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_n[0]}]
set_property -dict {PACKAGE_PIN H20 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_p[0]}]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_n[10]}]
set_property -dict {PACKAGE_PIN K17 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_p[10]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_n[1]}]
set_property -dict {PACKAGE_PIN G17 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_p[1]}]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_n[2]}]
set_property -dict {PACKAGE_PIN J19 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_p[2]}]
set_property -dict {PACKAGE_PIN L20 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_n[3]}]
set_property -dict {PACKAGE_PIN L19 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_p[3]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_n[4]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_p[4]}]
set_property -dict {PACKAGE_PIN M22 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_n[5]}]
set_property -dict {PACKAGE_PIN N22 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_p[5]}]
set_property -dict {PACKAGE_PIN L21 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_n[6]}]
set_property -dict {PACKAGE_PIN M21 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_p[6]}]
set_property -dict {PACKAGE_PIN J21 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_n[7]}]
set_property -dict {PACKAGE_PIN J20 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_p[7]}]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_n[8]}]
set_property -dict {PACKAGE_PIN N20 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_p[8]}]
set_property -dict {PACKAGE_PIN K22 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_n[9]}]
set_property -dict {PACKAGE_PIN K21 IOSTANDARD PPDS_25} [get_ports {sampa2_sdo_p[9]}]

# SAMPA 3

set_property -dict {PACKAGE_PIN K19 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_n[3]}]
set_property -dict {PACKAGE_PIN K18 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_p[3]}]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_n[0]}]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_p[0]}]
set_property -dict {PACKAGE_PIN G13 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_n[10]}]
set_property -dict {PACKAGE_PIN H13 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_p[10]}]
set_property -dict {PACKAGE_PIN L15 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_n[1]}]
set_property -dict {PACKAGE_PIN L14 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_p[1]}]
set_property -dict {PACKAGE_PIN M16 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_n[2]}]
set_property -dict {PACKAGE_PIN M15 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_p[2]}]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_n[3]}]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_p[3]}]
set_property -dict {PACKAGE_PIN G16 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_n[4]}]
set_property -dict {PACKAGE_PIN G15 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_p[4]}]
set_property -dict {PACKAGE_PIN H14 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_n[5]}]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_p[5]}]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_n[6]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_p[6]}]
set_property -dict {PACKAGE_PIN N19 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_n[7]}]
set_property -dict {PACKAGE_PIN N18 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_p[7]}]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_n[8]}]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_p[8]}]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_n[9]}]
set_property -dict {PACKAGE_PIN M18 IOSTANDARD PPDS_25} [get_ports {sampa3_sdo_p[9]}]

# SAMPA 4

set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_n[4]}]
set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_p[4]}]
set_property -dict {PACKAGE_PIN W7 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_n[0]}]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_p[0]}]
set_property -dict {PACKAGE_PIN V5 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_n[10]}]
set_property -dict {PACKAGE_PIN U6 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_p[10]}]
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_n[1]}]
set_property -dict {PACKAGE_PIN AA8 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_p[1]}]
set_property -dict {PACKAGE_PIN Y7 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_n[2]}]
set_property -dict {PACKAGE_PIN Y8 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_p[2]}]
set_property -dict {PACKAGE_PIN AA6 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_n[3]}]
set_property -dict {PACKAGE_PIN Y6 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_p[3]}]
set_property -dict {PACKAGE_PIN AB5 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_n[4]}]
set_property -dict {PACKAGE_PIN AA5 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_p[4]}]
set_property -dict {PACKAGE_PIN T6 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_n[5]}]
set_property -dict {PACKAGE_PIN R6 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_p[5]}]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_n[6]}]
set_property -dict {PACKAGE_PIN AB7 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_p[6]}]
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_n[7]}]
set_property -dict {PACKAGE_PIN W9 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_p[7]}]
set_property -dict {PACKAGE_PIN W5 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_n[8]}]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_p[8]}]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_n[9]}]
set_property -dict {PACKAGE_PIN V9 IOSTANDARD PPDS_25} [get_ports {sampa4_sdo_p[9]}]

# SAMPA 5

set_property -dict {PACKAGE_PIN W4 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_n[5]}]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_p[5]}]
set_property -dict {PACKAGE_PIN AB2 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_n[0]}]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_p[0]}]
set_property -dict {PACKAGE_PIN U1 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_n[10]}]
set_property -dict {PACKAGE_PIN T1 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_p[10]}]
set_property -dict {PACKAGE_PIN AA3 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_n[1]}]
set_property -dict {PACKAGE_PIN Y3 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_p[1]}]
set_property -dict {PACKAGE_PIN Y2 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_n[2]}]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_p[2]}]
set_property -dict {PACKAGE_PIN Y1 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_n[3]}]
set_property -dict {PACKAGE_PIN W1 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_p[3]}]
set_property -dict {PACKAGE_PIN AB1 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_n[4]}]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_p[4]}]
set_property -dict {PACKAGE_PIN V3 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_n[5]}]
set_property -dict {PACKAGE_PIN U3 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_p[5]}]
set_property -dict {PACKAGE_PIN V2 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_n[6]}]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_p[6]}]
set_property -dict {PACKAGE_PIN T4 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_n[7]}]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_p[7]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_n[8]}]
set_property -dict {PACKAGE_PIN R3 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_p[8]}]
set_property -dict {PACKAGE_PIN AA4 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_n[9]}]
set_property -dict {PACKAGE_PIN Y4 IOSTANDARD PPDS_25} [get_ports {sampa5_sdo_p[9]}]

# SAMPA 6

set_property -dict {PACKAGE_PIN J4 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_n[6]}]
set_property -dict {PACKAGE_PIN K4 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_p[6]}]
set_property -dict {PACKAGE_PIN N2 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_n[0]}]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_p[0]}]
set_property -dict {PACKAGE_PIN J1 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_n[10]}]
set_property -dict {PACKAGE_PIN K1 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_p[10]}]
set_property -dict {PACKAGE_PIN P1 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_n[1]}]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_p[1]}]
set_property -dict {PACKAGE_PIN M5 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_n[2]}]
set_property -dict {PACKAGE_PIN M6 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_p[2]}]
set_property -dict {PACKAGE_PIN L4 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_n[3]}]
set_property -dict {PACKAGE_PIN L5 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_p[3]}]
set_property -dict {PACKAGE_PIN M2 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_n[4]}]
set_property -dict {PACKAGE_PIN M3 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_p[4]}]
set_property -dict {PACKAGE_PIN L1 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_n[5]}]
set_property -dict {PACKAGE_PIN M1 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_p[5]}]
set_property -dict {PACKAGE_PIN K3 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_n[6]}]
set_property -dict {PACKAGE_PIN L3 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_p[6]}]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_n[7]}]
set_property -dict {PACKAGE_PIN P5 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_p[7]}]
set_property -dict {PACKAGE_PIN J2 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_n[8]}]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_p[8]}]
set_property -dict {PACKAGE_PIN N5 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_n[9]}]
set_property -dict {PACKAGE_PIN P6 IOSTANDARD PPDS_25} [get_ports {sampa6_sdo_p[9]}]

# SAMPA 7

set_property -dict {PACKAGE_PIN G4 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_n[7]}]
set_property -dict {PACKAGE_PIN H4 IOSTANDARD LVDS_25} [get_ports {sampa_sdo_clk_p[7]}]
set_property -dict {PACKAGE_PIN N3 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_n[0]}]
set_property -dict {PACKAGE_PIN N4 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_p[0]}]
set_property -dict {PACKAGE_PIN A1 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_n[10]}]
set_property -dict {PACKAGE_PIN B1 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_p[10]}]
set_property -dict {PACKAGE_PIN G3 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_n[1]}]
set_property -dict {PACKAGE_PIN H3 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_p[1]}]
set_property -dict {PACKAGE_PIN G2 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_n[2]}]
set_property -dict {PACKAGE_PIN H2 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_p[2]}]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_n[3]}]
set_property -dict {PACKAGE_PIN F3 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_p[3]}]
set_property -dict {PACKAGE_PIN F1 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_n[4]}]
set_property -dict {PACKAGE_PIN G1 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_p[4]}]
set_property -dict {PACKAGE_PIN D2 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_n[5]}]
set_property -dict {PACKAGE_PIN E2 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_p[5]}]
set_property -dict {PACKAGE_PIN D1 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_n[6]}]
set_property -dict {PACKAGE_PIN E1 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_p[6]}]
set_property -dict {PACKAGE_PIN H5 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_n[7]}]
set_property -dict {PACKAGE_PIN J5 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_p[7]}]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_n[8]}]
set_property -dict {PACKAGE_PIN C2 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_p[8]}]
set_property -dict {PACKAGE_PIN J6 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_n[9]}]
set_property -dict {PACKAGE_PIN K6 IOSTANDARD PPDS_25} [get_ports {sampa7_sdo_p[9]}]

# I2C Busses

set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS25} [get_ports sampa_i2c_scl]
set_property -dict {PACKAGE_PIN N13 IOSTANDARD LVCMOS25} [get_ports sampa_i2c_sda]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS25} [get_ports sfp_i2c_sda]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS25} [get_ports sfp_i2c_scl]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS25} [get_ports si5338_i2c_scl]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS25} [get_ports si5338_i2c_sda]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS25} [get_ports temperature_i2c_scl]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS25} [get_ports temperature_i2c_sda]
set_property -dict {PACKAGE_PIN P17 IOSTANDARD LVCMOS25} [get_ports vimon_i2c_scl]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS25} [get_ports vimon_i2c_sda]

